[build]
  # No build command needed for static site
  command = ""
  # Publish directory - this is where your built files should be
  publish = "docs"

[build.environment]
  # Set the Node.js version
  NODE_VERSION = "16"
  # Skip build if there's no build command
  NPM_FLAGS = "--prefix=$NETLIFY_BUILD_BASE"
  NPM_LIBS = ""

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
