version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carers-care-api
    restart: unless-stopped
    env_file:
      - ./config/config.env
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/public/uploads
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config_data:
