version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carers-care-api
    restart: unless-stopped
    env_file:
      - ./config/config.env
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/carers_care
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/public/uploads
    depends_on:
      - mongo
    networks:
      - app-network
    command: npm run dev

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=carers_care
    volumes:
      - mongodb_data:/data/db
      - mongodb_config_data:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config_data:
